import type { Achievement } from './types'

export const achievements: Achievement[] = [
  {
    id: 'first-run',
    name: 'First Blood',
    description: 'Run your first program',
    icon: '⚡',
    rarity: 'common',
  },
  {
    id: 'hello-world',
    name: 'Hello World',
    description: 'Print "hello world"',
    icon: '👋',
    rarity: 'common',
  },
  {
    id: 'polyglot',
    name: 'Polyglot',
    description: 'Run code in both JavaScript and Python',
    icon: '🌍',
    rarity: 'rare',
  },
  {
    id: 'block-party',
    name: 'Block Party',
    description: 'Use 50+ blocks in one program',
    icon: '🎉',
    rarity: 'rare',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Code between 11pm and 5am',
    icon: '🦉',
    rarity: 'rare',
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Complete a challenge in under 30 seconds',
    icon: '💨',
    rarity: 'epic',
  },
  {
    id: 'eagle-eye',
    name: 'Eagle Eye',
    description: 'Get 3 stars on a challenge',
    icon: '🦅',
    rarity: 'rare',
  },
  {
    id: 'easter-egg-hunter',
    name: 'Easter Egg Hunter',
    description: 'Activate hacker mode',
    icon: '🥚',
    rarity: 'epic',
    secret: true,
  },
  {
    id: 'code-golfer',
    name: 'Code Golfer',
    description: 'Complete a Code Golf problem',
    icon: '⛳',
    rarity: 'rare',
  },
  {
    id: 'lab-rat',
    name: 'Lab Rat',
    description: 'Complete a Code Lab exercise',
    icon: '🐀',
    rarity: 'common',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Run 100 programs',
    icon: '💯',
    rarity: 'epic',
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Create a custom block',
    icon: '🏗️',
    rarity: 'rare',
  },
  {
    id: 'turtle-power',
    name: 'Pen Power',
    description: 'Use a Pen block',
    icon: '🖊️',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'mad-scientist',
    name: 'Mad Scientist',
    description: 'Use blocks from 5+ categories in one program',
    icon: '🧪',
    rarity: 'epic',
  },
  {
    id: 'the-answer',
    name: 'The Answer',
    description: 'Print exactly "42"',
    icon: '🌌',
    rarity: 'legendary',
    secret: true,
  },
]
