import type { Achievement } from './types'

export const achievements: Achievement[] = [
  {
    id: 'first-run',
    name: 'First Blood',
    description: 'Run your first program',
    icon: '⚡',
    rarity: 'common',
  },
  {
    id: 'hello-world',
    name: 'Hello World',
    description: 'Print "hello world"',
    icon: '👋',
    rarity: 'common',
  },
  {
    id: 'polyglot',
    name: 'Polyglot',
    description: 'Run code in both JavaScript and Python',
    icon: '🌍',
    rarity: 'rare',
  },
  {
    id: 'block-party',
    name: 'Block Party',
    description: 'Use 50+ blocks in one program',
    icon: '🎉',
    rarity: 'rare',
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Code between 11pm and 5am',
    icon: '🦉',
    rarity: 'rare',
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Complete a challenge in under 30 seconds',
    icon: '💨',
    rarity: 'epic',
  },
  {
    id: 'eagle-eye',
    name: 'Eagle Eye',
    description: 'Get 3 stars on a challenge',
    icon: '🦅',
    rarity: 'rare',
  },
  {
    id: 'easter-egg-hunter',
    name: 'Easter Egg Hunter',
    description: 'Activate hacker mode',
    icon: '🥚',
    rarity: 'epic',
    secret: true,
  },
  {
    id: 'code-golfer',
    name: 'Code Golfer',
    description: 'Complete a Code Golf problem',
    icon: '⛳',
    rarity: 'rare',
  },
  {
    id: 'lab-rat',
    name: 'Lab Rat',
    description: 'Complete a Code Lab exercise',
    icon: '🐀',
    rarity: 'common',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Run 100 programs',
    icon: '💯',
    rarity: 'epic',
  },
  {
    id: 'architect',
    name: 'Architect',
    description: 'Create a custom block',
    icon: '🏗️',
    rarity: 'rare',
  },
  {
    id: 'turtle-power',
    name: 'Pen Power',
    description: 'Use a Pen block',
    icon: '🖊️',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'mad-scientist',
    name: 'Mad Scientist',
    description: 'Use blocks from 5+ categories in one program',
    icon: '🧪',
    rarity: 'epic',
  },
  {
    id: 'the-answer',
    name: 'The Answer',
    description: 'Print exactly "42"',
    icon: '🌌',
    rarity: 'legendary',
    secret: true,
  },

  // === v0.3 Achievements ===

  // Collab
  {
    id: 'team-player',
    name: 'Team Player',
    description: 'Join a collab room',
    icon: '🤝',
    rarity: 'common',
  },
  {
    id: 'teacher-mode',
    name: 'Teacher Mode',
    description: 'Create a classroom',
    icon: '🏫',
    rarity: 'rare',
  },

  // Games
  {
    id: 'game-on',
    name: 'Game On',
    description: 'Run a program with game blocks',
    icon: '🎮',
    rarity: 'common',
  },
  {
    id: 'level-designer',
    name: 'Level Designer',
    description: 'Export a level from the Level Editor',
    icon: '🗺️',
    rarity: 'rare',
  },
  {
    id: 'pixel-artist',
    name: 'Pixel Artist',
    description: 'Save a sprite in the Sprite Editor',
    icon: '🎨',
    rarity: 'common',
  },

  // AI
  {
    id: 'voice-activated',
    name: 'Voice Activated',
    description: 'Use a speech block',
    icon: '🎤',
    rarity: 'rare',
  },
  {
    id: 'i-see-you',
    name: 'I See You',
    description: 'Classify an image with MobileNet',
    icon: '👁️',
    rarity: 'epic',
  },

  // Hardware
  {
    id: 'hardware-hacker',
    name: 'Hardware Hacker',
    description: 'Connect a micro:bit',
    icon: '🔌',
    rarity: 'epic',
  },

  // Daily Challenge
  {
    id: 'daily-starter',
    name: 'Daily Starter',
    description: 'Solve your first Daily Challenge',
    icon: '🎯',
    rarity: 'common',
  },
  {
    id: 'streak-3',
    name: 'Three-peat',
    description: 'Get a 3-day Daily Challenge streak',
    icon: '🔥',
    rarity: 'rare',
  },
  {
    id: 'streak-7',
    name: 'On Fire',
    description: 'Get a 7-day Daily Challenge streak',
    icon: '🔥🔥',
    rarity: 'epic',
  },
  {
    id: 'streak-30',
    name: 'Unstoppable',
    description: 'Get a 30-day Daily Challenge streak',
    icon: '🏆',
    rarity: 'legendary',
  },

  // Shareplace
  {
    id: 'first-share',
    name: 'First Share',
    description: 'Upload your first project to Shareplace',
    icon: '📤',
    rarity: 'common',
  },
  {
    id: 'popular',
    name: 'Popular',
    description: 'Get 10 likes on a project',
    icon: '❤️',
    rarity: 'rare',
  },
  {
    id: 'hello-indeed',
    name: 'Hello Indeed',
    description: 'Remix the Hello World example — your journey begins!',
    icon: '🌟',
    rarity: 'legendary',
    secret: true,
  },

  // === Hidden Seeds — hackable easter eggs ===
  {
    id: 'deep-thought',
    name: 'Deep Thought',
    description: 'The answer to life, the universe, and everything',
    icon: '🧠',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'taxicab',
    name: 'Taxicab',
    description: 'The smallest number expressible as the sum of two cubes in two ways',
    icon: '🚕',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'elite',
    name: '1337',
    description: '1337 h4x0r',
    icon: '💀',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'phreaker',
    name: 'Phreaker',
    description: '2600 Hz — if you know, you know',
    icon: '📞',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'not-found',
    name: '404',
    description: 'Or was it?',
    icon: '👻',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'remixer',
    name: 'Remixer',
    description: 'Remix another project',
    icon: '🔀',
    rarity: 'common',
  },
  {
    id: 'inspiration',
    name: 'Inspiration',
    description: 'Someone remixed your project',
    icon: '✨',
    rarity: 'epic',
  },

  // Prestige / Milestones
  {
    id: 'marathon',
    name: 'Marathon',
    description: 'Run 500 programs',
    icon: '🏃',
    rarity: 'epic',
  },
  {
    id: 'thousand-runs',
    name: 'Millennial',
    description: 'Run 1000 programs',
    icon: '🎖️',
    rarity: 'legendary',
  },
  {
    id: 'block-master',
    name: 'Block Master',
    description: 'Use 100+ blocks in one program',
    icon: '🧩',
    rarity: 'legendary',
  },
  {
    id: 'block-1000',
    name: 'Megastructure',
    description: 'Use 1,000+ blocks in one program',
    icon: '🏰',
    rarity: 'legendary',
  },
  {
    id: 'block-2500',
    name: 'Digital Architect',
    description: 'Use 2,500+ blocks in one program',
    icon: '🌐',
    rarity: 'legendary',
  },
  {
    id: 'block-5000',
    name: 'Block Titan',
    description: 'Use 5,000+ blocks in one program',
    icon: '⚡',
    rarity: 'legendary',
  },
  {
    id: 'block-god',
    name: 'Block God',
    description: 'Use 7,500+ blocks in one program',
    icon: '👑',
    rarity: 'legendary',
  },
  {
    id: 'block-10000',
    name: 'The Architect',
    description: 'Use 10,000+ blocks in one program',
    icon: '🔱',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'all-categories',
    name: 'Renaissance Coder',
    description: 'Use blocks from 10+ categories in one program',
    icon: '🎭',
    rarity: 'legendary',
  },
  {
    id: 'time-traveler',
    name: 'Time Traveler',
    description: 'Use Time Travel to scrub through your history',
    icon: '🕰️',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'matrix',
    name: 'Red Pill',
    description: 'Enter the Matrix',
    icon: '💊',
    rarity: 'legendary',
    secret: true,
  },

  // === v0.4 — Terminal easter egg achievements ===
  // === Crypto ===
  {
    id: 'multi-platformer',
    name: 'The Multi-Platformer',
    description: 'Import a project from Scratch',
    icon: '🐱',
    rarity: 'epic',
  },
  {
    id: 'napster',
    name: 'Napster',
    description: 'Import 10 projects from Scratch',
    icon: '🎵',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'going-global',
    name: 'Going Global',
    description: 'Publish a project to GitHub',
    icon: '🌍',
    rarity: 'epic',
  },
  {
    id: 'contributor',
    name: 'The Contributor',
    description: 'Share 30 projects to Shareplace',
    icon: '🫡',
    rarity: 'legendary',
  },
  {
    id: 'trendsetter',
    name: 'Trendsetter',
    description: 'Have your projects remixed 5 times',
    icon: '🌊',
    rarity: 'rare',
  },
  {
    id: 'influencer',
    name: 'The Influencer',
    description: 'Have your projects remixed 30 times',
    icon: '📣',
    rarity: 'legendary',
  },
  {
    id: 'pi',
    name: 'Irrational',
    description: 'Place 31,415 blocks — the first 5 digits of Pi',
    icon: '🥧',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'finney',
    name: 'Finney',
    description: 'Use 6 unique Crypto blocks in one program',
    icon: '🔐',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'satoshi',
    name: 'Satoshi',
    description: 'Use 8 unique Crypto blocks in one program',
    icon: '₿',
    rarity: 'epic',
    secret: true,
  },

  // === Version Control ===
  {
    id: 'first-commit',
    name: 'First Commit',
    description: 'Save your first checkpoint',
    icon: '💾',
    rarity: 'common',
  },
  {
    id: 'historian',
    name: 'Historian',
    description: 'Save 10 checkpoints',
    icon: '📜',
    rarity: 'rare',
  },
  {
    id: 'brancher',
    name: 'Brancher',
    description: 'Create a branch from history',
    icon: '🌿',
    rarity: 'rare',
  },
  {
    id: 'merger',
    name: 'Merger',
    description: 'Merge a branch',
    icon: '🔀',
    rarity: 'epic',
  },
  {
    id: 'time-lord',
    name: 'Time Lord',
    description: 'Save 50 checkpoints',
    icon: '⏳',
    rarity: 'epic',
  },

  // === Block Placement Milestones ===
  {
    id: 'mile-placer',
    name: 'Mile Placer',
    description: 'Place 1,600 blocks',
    icon: '🧱',
    rarity: 'rare',
  },
  {
    id: 'block-5k',
    name: '5K Runner',
    description: 'Place 5,000 blocks',
    icon: '🏃',
    rarity: 'rare',
  },
  {
    id: 'block-10k',
    name: '10K Club',
    description: 'Place 10,000 blocks',
    icon: '🏗️',
    rarity: 'rare',
  },
  {
    id: 'block-25k',
    name: 'Quarter Century',
    description: 'Place 25,000 blocks',
    icon: '🏛️',
    rarity: 'epic',
  },
  {
    id: 'block-50k',
    name: 'Block City',
    description: 'Place 50,000 blocks',
    icon: '🌆',
    rarity: 'epic',
  },
  {
    id: 'moon-walker',
    name: 'Moon Walker',
    description: 'Place 238,900 blocks — the distance to the moon in miles',
    icon: '🌙',
    rarity: 'legendary',
  },

  // === Green Cube Collectors ===
  {
    id: 'green-cube-01',
    name: 'Green Cube Collector 01',
    description: '7 active days on the heatmap',
    icon: '🟩',
    rarity: 'rare',
  },
  {
    id: 'green-cube-02',
    name: 'Green Cube Collector 02',
    description: '50 active days in a 90-day window',
    icon: '🟩',
    rarity: 'epic',
  },
  {
    id: 'green-cube-03',
    name: 'Green Cube Collector 03',
    description: '180 active days in one year',
    icon: '🟩',
    rarity: 'legendary',
  },

  {
    id: 'the-cake',
    name: 'The Cake Is A Lie',
    description: 'You asked for cake.',
    icon: '🎂',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'doom-slayer',
    name: 'Doom Slayer',
    description: 'Clear Level 1 of CryptDOOM',
    icon: '💀',
    rarity: 'epic',
    secret: true,
  },
  {
    id: 'doom-veteran',
    name: 'Doom Veteran',
    description: 'Reach Level 5 of CryptDOOM',
    icon: '🔥',
    rarity: 'legendary',
    secret: true,
  },
  {
    id: 'egg-hunter',
    name: 'Egg Hunter',
    description: 'Open the Egg Vault',
    icon: '🥚',
    rarity: 'rare',
    secret: true,
  },
  {
    id: 'snek',
    name: 'Snek',
    description: 'Play Snake',
    icon: '🐍',
    rarity: 'common',
    secret: true,
  },
  {
    id: 'space-cadet',
    name: 'Space Cadet',
    description: 'Play Space Invaders',
    icon: '👾',
    rarity: 'common',
    secret: true,
  },
]
