import { describe, it, expect } from 'vitest'
// @ts-expect-error — pure ESM JS module, no .d.ts
import { toSeniorDev } from '../seniordev-transform.mjs'

const norm = (s: string) => s.replace(/\s+$/g, '').replace(/\r\n/g, '\n')

describe('toSeniorDev', () => {
  it('strips CryptoBlocks boilerplate headers and source-map markers', () => {
    const input = `// Generated by CryptoBlocks

// --- Block Definitions ---
function print(message) {
  console.log(message);
}

// --- Program ---
/*__cb:abc123*/
print("hi");
`
    const out = toSeniorDev(input)
    expect(out).not.toContain('Generated by CryptoBlocks')
    expect(out).not.toContain('Block Definitions')
    expect(out).not.toContain('Program ---')
    expect(out).not.toContain('__cb:')
    expect(norm(out)).toBe('console.log("hi");')
  })

  it('inlines the coin-flip example into idiomatic JS', () => {
    const input = `// Generated by CryptoBlocks

// --- Block Definitions ---
function greaterThan(a, b) {
  return a > b;
}

function randomNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function print(message) {
  console.log(message);
}

// --- Program ---
if (greaterThan(randomNumber(1, 2), 1)) {
  print("Heads!");
} else {
  print("Tails!");
}
`
    const out = norm(toSeniorDev(input))
    // No wrapper definitions left.
    expect(out).not.toMatch(/function\s+(greaterThan|randomNumber|print)\b/)
    // Calls collapsed.
    expect(out).not.toMatch(/\b(greaterThan|randomNumber|print)\s*\(/)
    // Constant folding: (max - min + 1) with min=1, max=2 -> 2.
    expect(out).toContain('Math.random() * 2')
    // If/else collapsed into a ternary inside a single console.log.
    expect(out).toContain('console.log(')
    expect(out).toContain('? "Heads!" : "Tails!"')
    expect(out.split('\n').filter(l => l.trim() === 'console.log(').length).toBe(0)
  })

  it('inlines nested arithmetic wrappers and folds constants', () => {
    const input = `// Generated by CryptoBlocks

// --- Block Definitions ---
function add(a, b) {
  return a + b;
}

function multiply(a, b) {
  return a * b;
}

// --- Program ---
console.log(add(multiply(2, 3), 4));
`
    const out = norm(toSeniorDev(input))
    // 2*3=6, 6+4=10 — fully folded.
    expect(out).toBe('console.log(10);')
  })

  it('inlines pure-identifier returns without extra parens', () => {
    const input = `function doValue(value) {
  return value;
}

console.log(doValue("hello"));
`
    const out = norm(toSeniorDev(input))
    expect(out).toBe('console.log("hello");')
  })

  it('leaves wrappers in place when arity does not match (defensive)', () => {
    const input = `function add(a, b) {
  return a + b;
}

console.log(add(1, 2, 3));
`
    const out = norm(toSeniorDev(input))
    // Mismatched arity → call left alone, wrapper kept.
    expect(out).toContain('function add')
    expect(out).toContain('add(1, 2, 3)')
  })

  it('inlines method-call bodies without wrapping in parens', () => {
    const input = `function uppercase(text) {
  return text.toUpperCase();
}

console.log(uppercase("ok"));
`
    const out = norm(toSeniorDev(input))
    expect(out).toBe('console.log("ok".toUpperCase());')
  })

  it('keeps if/else when branches are not single matching calls', () => {
    const input = `function print(message) {
  console.log(message);
}

if (x > 0) {
  print("a");
  print("b");
} else {
  print("c");
}
`
    const out = norm(toSeniorDev(input))
    expect(out).toContain('if (x > 0)')
    expect(out).toContain('console.log("a")')
    expect(out).toContain('console.log("b")')
    expect(out).toContain('console.log("c")')
    // No ternary — branch shapes differ.
    expect(out).not.toMatch(/console\.log\(.*\?.*:.*\)/)
  })
})
