import * as Blockly from 'blockly'
import type { BlockDefinition, Language } from '../types/block'
import { registry } from './registry'

function typeToBlocklyField(type: string): string {
  switch (type) {
    case 'number':
      return 'NUM'
    case 'boolean':
      return 'BOOL'
    default:
      return 'TEXT'
  }
}

function typeToBlocklyCheck(type: string): string | null {
  switch (type) {
    case 'number':
      return 'Number'
    case 'boolean':
      return 'Boolean'
    case 'string':
      return 'String'
    default:
      return null
  }
}

export function registerCustomBlocks() {
  const allBlocks = registry.getAll()

  for (const block of allBlocks) {
    const blockType = `cb_${block.name}`

    Blockly.Blocks[blockType] = {
      init: function (this: Blockly.Block) {
        this.setColour(block.color)
        this.setTooltip(block.description)

        // Add block name as label
        this.appendDummyInput().appendField(
          block.name.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
        )

        // Add inputs
        for (const input of block.inputs) {
          const check = typeToBlocklyCheck(input.type)
          const inputObj = this.appendValueInput(input.name)
          inputObj.appendField(input.name.replace(/_/g, ' '))
          if (check) inputObj.setCheck(check)
        }

        // Add output or set as statement based on shape override or outputs
        const isValue = block.shape === 'value' || (!block.shape && block.outputs.length > 0)
        if (isValue) {
          const outCheck = block.outputs.length > 0 ? typeToBlocklyCheck(block.outputs[0].type) : null
          this.setOutput(true, outCheck)
        } else {
          this.setPreviousStatement(true, null)
          this.setNextStatement(true, null)
        }
      },
    }
  }
}

export function registerSingleBlock(block: BlockDefinition) {
  const blockType = `cb_${block.name}`

  Blockly.Blocks[blockType] = {
    init: function (this: Blockly.Block) {
      this.setColour(block.color)
      this.setTooltip(block.description)

      this.appendDummyInput().appendField(
        block.name.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
      )

      for (const input of block.inputs) {
        const check = typeToBlocklyCheck(input.type)
        const inputObj = this.appendValueInput(input.name)
        inputObj.appendField(input.name.replace(/_/g, ' '))
        if (check) inputObj.setCheck(check)
      }

      const isValue = block.shape === 'value' || (!block.shape && block.outputs.length > 0)
      if (isValue) {
        const outCheck = block.outputs.length > 0 ? typeToBlocklyCheck(block.outputs[0].type) : null
        this.setOutput(true, outCheck)
      } else {
        this.setPreviousStatement(true, null)
        this.setNextStatement(true, null)
      }
    },
  }
}

export function generateCode(workspace: Blockly.Workspace, language: Language): string {
  const topBlocks = workspace.getTopBlocks(true)
  const lines: string[] = []

  if (language === 'javascript') {
    lines.push('// Generated by CryptoBlocks')
    lines.push('')
  } else {
    lines.push('# Generated by CryptoBlocks')
    lines.push('')
  }

  // Collect all used block definitions
  const usedBlocks = new Set<string>()
  function collectBlocks(block: Blockly.Block) {
    if (!isBuiltinBlock(block.type)) {
      const name = block.type.replace('cb_', '')
      usedBlocks.add(name)
    }
    for (const input of block.inputList) {
      if (input.connection) {
        const connected = input.connection.targetBlock()
        if (connected) collectBlocks(connected)
      }
    }
    const next = block.getNextBlock()
    if (next) collectBlocks(next)
  }
  topBlocks.forEach(collectBlocks)

  // Add function definitions for used blocks
  if (language === 'javascript') {
    lines.push('// --- Block Definitions ---')
  } else {
    lines.push('# --- Block Definitions ---')
  }

  for (const name of usedBlocks) {
    const def = registry.get(name)
    if (def) {
      lines.push(def.implementations[language])
      lines.push('')
    }
  }

  // Generate the execution code
  if (language === 'javascript') {
    lines.push('// --- Program ---')
  } else {
    lines.push('# --- Program ---')
  }

  for (const topBlock of topBlocks) {
    lines.push(generateBlockCode(topBlock, language))
  }

  return lines.join('\n')
}

function generateBuiltinCode(block: Blockly.Block, language: Language): string | null {
  switch (block.type) {
    case 'text':
      return JSON.stringify(block.getFieldValue('TEXT') ?? '')
    case 'math_number':
      return String(block.getFieldValue('NUM') ?? 0)
    case 'logic_boolean':
      const val = block.getFieldValue('BOOL') === 'TRUE'
      return language === 'javascript' ? String(val) : (val ? 'True' : 'False')
    default:
      return null
  }
}

function isBuiltinBlock(type: string): boolean {
  return ['text', 'math_number', 'logic_boolean'].includes(type)
}

function generateBlockCode(block: Blockly.Block, language: Language): string {
  // Handle built-in Blockly value blocks first
  const builtin = generateBuiltinCode(block, language)
  if (builtin !== null) return builtin

  const name = block.type.replace('cb_', '')
  const def = registry.get(name)

  if (!def) {
    const comment = language === 'javascript' ? '//' : '#'
    return `${comment} Unknown block: ${name}`
  }

  // Get the function name from the implementation
  const fnName = extractFunctionName(def, language)

  // Build arguments from connected inputs
  const args: string[] = []
  for (const input of def.inputs) {
    const inputBlock = block.getInputTargetBlock(input.name)
    if (inputBlock) {
      args.push(generateBlockCode(inputBlock, language))
    } else {
      // Use default or placeholder
      const defaultVal = input.default
      if (defaultVal !== undefined) {
        args.push(typeof defaultVal === 'string' ? `"${defaultVal}"` : String(defaultVal))
      } else {
        switch (input.type) {
          case 'string':
            args.push('""')
            break
          case 'number':
            args.push('0')
            break
          case 'boolean':
            args.push(language === 'javascript' ? 'false' : 'False')
            break
          default:
            args.push(language === 'javascript' ? 'null' : 'None')
        }
      }
    }
  }

  const isAsync = def.implementations[language].trimStart().startsWith('async ')
  let code = isAsync ? `await ${fnName}(${args.join(', ')})` : `${fnName}(${args.join(', ')})`

  // If this is a statement block, make it a standalone call
  const isStatement = def.shape === 'statement' || (!def.shape && def.outputs.length === 0)
  if (isStatement) {
    code += language === 'javascript' ? ';' : ''
  }

  // Handle chained (next) blocks
  const nextBlock = block.getNextBlock()
  if (nextBlock) {
    code += '\n' + generateBlockCode(nextBlock, language)
  }

  return code
}

function extractFunctionName(def: BlockDefinition, language: Language): string {
  const code = def.implementations[language]
  if (language === 'javascript') {
    const match = code.match(/function\s+(\w+)/)
    return match ? match[1] : def.name
  } else {
    const match = code.match(/def\s+(\w+)/)
    return match ? match[1] : def.name
  }
}

export function getToolboxXml(): string {
  const categories = registry.getCategories()
  let xml = '<xml>'

  for (const cat of categories) {
    const blocks = registry.getByCategory(cat)
    const color = registry.getCategoryColor(cat)
    // Convert hex color to Blockly hue (0-360)
    const hue = hexToHue(color)
    xml += `<category name="${cat}" colour="${hue}">`

    for (const block of blocks) {
      xml += `<block type="cb_${block.name}">`
      // Add shadow blocks for inputs with defaults
      for (const input of block.inputs) {
        if (input.default !== undefined) {
          const fieldType = typeToBlocklyField(input.type)
          xml += `<value name="${input.name}">`
          if (input.type === 'number') {
            xml += `<shadow type="math_number"><field name="${fieldType}">${input.default}</field></shadow>`
          } else if (input.type === 'string') {
            xml += `<shadow type="text"><field name="${fieldType}">${input.default}</field></shadow>`
          }
          xml += `</value>`
        }
      }
      xml += `</block>`
    }

    xml += '</category>'
  }

  // Add built-in Blockly blocks for values
  xml += '<sep></sep>'
  xml += '<category name="Values" colour="230">'
  xml += '<block type="math_number"><field name="NUM">0</field></block>'
  xml += '<block type="text"><field name="TEXT">hello</field></block>'
  xml += '<block type="logic_boolean"><field name="BOOL">TRUE</field></block>'
  xml += '</category>'

  xml += '</xml>'
  return xml
}

function hexToHue(hex: string): number {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255

  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  let h = 0

  if (max !== min) {
    const d = max - min
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) / 6
        break
      case g:
        h = ((b - r) / d + 2) / 6
        break
      case b:
        h = ((r - g) / d + 4) / 6
        break
    }
  }

  return Math.round(h * 360)
}
