[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.147.4"
  NODE_VERSION = "20"

[[redirects]]
  from = "/app"
  to = "https://app.cryptoblocks.dev"
  status = 301

[[redirects]]
  from = "/app/*"
  to = "https://app.cryptoblocks.dev/:splat"
  status = 301
