import type { BlockDefinition } from '../../types/block'

export const basicsBlocks: BlockDefinition[] = [
  {
    name: 'print',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Print a message to the output',
    category: 'Basics',
    inputs: [{ name: 'message', type: 'any', description: 'The message to print' }],
    outputs: [],
    implementations: {
      javascript: `function print(message) {\n  console.log(message);\n}`,
      python: `def print_message(message):\n    print(message)`,
    },
    tests: [
      { input: { message: 'Hello!' }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'do',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Run a value without printing it',
    category: 'Basics',
    inputs: [{ name: 'value', type: 'any', description: 'The value to evaluate' }],
    outputs: [],
    implementations: {
      javascript: `function doValue(value) {\n  return value;\n}`,
      python: `def do_value(value):\n    return value`,
    },
    tests: [
      { input: { value: 42 }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'ask',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Ask the user a question and get their answer',
    category: 'Basics',
    inputs: [{ name: 'question', type: 'string', description: 'The question to ask' }],
    outputs: [{ name: 'answer', type: 'string' }],
    implementations: {
      javascript: `function ask(question) {\n  return prompt(question) || "";\n}`,
      python: `def ask(question):\n    return input(question)`,
    },
    tests: [
      { input: { question: 'What is your name?' }, expected: { answer: 'string' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'return_value',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Return a value from a function',
    category: 'Basics',
    inputs: [
      { name: 'value', type: 'any', description: 'Value to return' },
    ],
    outputs: [],
    implementations: {
      javascript: `function returnValue(value) {\n  window.__localStack.pop();\n  throw { __cbReturn: true, value: value };\n}`,
      python: `class _CBReturn(Exception):\n    def __init__(self, value):\n        self.value = value\ndef return_value(value):\n    raise _CBReturn(value)`,
    },
    tests: [
      { input: { value: 42 }, expected: {} },
    ],
    color: '#4C97AF',
    shape: 'statement',
  },
  {
    name: 'set_local',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Store a value scoped to the current function',
    category: 'Basics',
    inputs: [
      { name: 'name', type: 'string', description: 'Variable name' },
      { name: 'value', type: 'any', description: 'Value to store' },
    ],
    outputs: [{ name: 'value', type: 'any' }],
    implementations: {
      javascript: `function setLocal(name, value) {\n  var scope = (window.__localStack || [{}]);\n  scope[scope.length - 1][name] = value;\n  return value;\n}`,
      python: `def set_local(name, value):\n    if not hasattr(set_local, '_stack') or not set_local._stack:\n        set_local._stack = [{}]\n    set_local._stack[-1][name] = value\n    return value`,
    },
    tests: [
      { input: { name: 'x', value: 42 }, expected: { value: 42 } },
    ],
    color: '#4C97AF',
    shape: 'statement',
  },
  {
    name: 'get_local',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get a value that was stored with Set Local',
    category: 'Basics',
    inputs: [{ name: 'name', type: 'string', description: 'Variable name' }],
    outputs: [{ name: 'value', type: 'any' }],
    implementations: {
      javascript: `function getLocal(name) {\n  var scope = (window.__localStack || [{}]);\n  return scope[scope.length - 1][name];\n}`,
      python: `def get_local(name):\n    if not hasattr(get_local, '_stack') or not get_local._stack:\n        return None\n    return get_local._stack[-1].get(name)`,
    },
    tests: [
      { input: { name: 'x' }, expected: { value: 'any' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'set_global',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Store a value that all blocks can access',
    category: 'Basics',
    inputs: [
      { name: 'name', type: 'string', description: 'Variable name' },
      { name: 'value', type: 'any', description: 'Value to store' },
    ],
    outputs: [{ name: 'value', type: 'any' }],
    implementations: {
      javascript: `function setGlobal(name, value) {\n  window.__vars = window.__vars || {};\n  window.__vars[name] = value;\n  return value;\n}`,
      python: `def set_global(name, value):\n    globals()[name] = value\n    return value`,
    },
    tests: [
      { input: { name: 'x', value: 42 }, expected: { value: 42 } },
    ],
    color: '#4C97AF',
    shape: 'statement',
  },
  {
    name: 'get_global',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get a value that was stored with Set Global',
    category: 'Basics',
    inputs: [{ name: 'name', type: 'string', description: 'Variable name' }],
    outputs: [{ name: 'value', type: 'any' }],
    implementations: {
      javascript: `function getGlobal(name) {\n  return (window.__vars || {})[name];\n}`,
      python: `def get_global(name):\n    return globals().get(name)`,
    },
    tests: [
      { input: { name: 'x' }, expected: { value: 'any' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'wait',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Wait for a number of seconds',
    category: 'Basics',
    inputs: [{ name: 'seconds', type: 'number', description: 'How many seconds to wait', default: 1 }],
    outputs: [],
    implementations: {
      javascript: `async function wait(seconds) {\n  await new Promise(r => setTimeout(r, seconds * 1000));\n}`,
      python: `import time\ndef wait(seconds):\n    time.sleep(seconds)`,
    },
    tests: [
      { input: { seconds: 1 }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'console_table',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Print a list or object as a formatted table',
    category: 'Basics',
    inputs: [
      { name: 'name', type: 'string', description: 'Name of the list or object to display' },
    ],
    outputs: [],
    implementations: {
      javascript: `function consoleTable(name) {\n  window.__vars = window.__vars || {};\n  var data = window.__vars[name];\n  if (Array.isArray(data)) {\n    console.log("┌─ " + name + " ─┐");\n    data.forEach(function(item, i) { console.log("│ [" + i + "] " + JSON.stringify(item)); });\n    console.log("└────────────┘");\n  } else if (data && typeof data === 'object') {\n    console.log("┌─ " + name + " ─┐");\n    Object.keys(data).forEach(function(key) { console.log("│ " + key + ": " + JSON.stringify(data[key])); });\n    console.log("└────────────┘");\n  } else {\n    console.log(name + ": " + data);\n  }\n}`,
      python: `def console_table(name):\n    data = globals().get(name)\n    if isinstance(data, list):\n        print(f"┌─ {name} ─┐")\n        for i, item in enumerate(data):\n            print(f"│ [{i}] {item}")\n        print("└────────────┘")\n    elif isinstance(data, dict):\n        print(f"┌─ {name} ─┐")\n        for key, val in data.items():\n            print(f"│ {key}: {val}")\n        print("└────────────┘")\n    else:\n        print(f"{name}: {data}")`,
    },
    tests: [
      { input: { name: 'myList' }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'set_timeout',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Run a function after a delay',
    category: 'Basics',
    inputs: [
      { name: 'fn_name', type: 'string', description: 'Function to call', default: 'myFunction' },
      { name: 'seconds', type: 'number', description: 'Seconds to wait', default: 1 },
    ],
    outputs: [],
    implementations: {
      javascript: `function setTimeout2(fnName, seconds) {\n  var fn = window[fnName];\n  if (typeof fn === 'function') setTimeout(fn, seconds * 1000);\n}`,
      python: `import threading\ndef set_timeout(fn_name, seconds):\n    fn = globals().get(fn_name)\n    if callable(fn):\n        threading.Timer(seconds, fn).start()`,
    },
    tests: [
      { input: { fn_name: 'myFunction', seconds: 1 }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'set_interval',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Run a function repeatedly at a fixed interval',
    category: 'Basics',
    inputs: [
      { name: 'fn_name', type: 'string', description: 'Function to call', default: 'myFunction' },
      { name: 'seconds', type: 'number', description: 'Seconds between calls', default: 1 },
    ],
    outputs: [],
    implementations: {
      javascript: `function setInterval2(fnName, seconds) {\n  var fn = window[fnName];\n  if (typeof fn === 'function') setInterval(fn, seconds * 1000);\n}`,
      python: `import threading\ndef set_interval(fn_name, seconds):\n    fn = globals().get(fn_name)\n    if callable(fn):\n        def loop():\n            fn()\n            threading.Timer(seconds, loop).start()\n        loop()`,
    },
    tests: [
      { input: { fn_name: 'myFunction', seconds: 1 }, expected: {} },
    ],
    color: '#4C97AF',
  },
  {
    name: 'now',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the current date and time as text',
    category: 'Basics',
    inputs: [],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function now() {\n  return new Date().toLocaleString();\n}`,
      python: `from datetime import datetime\ndef now():\n    return datetime.now().strftime("%m/%d/%Y, %I:%M:%S %p")`,
    },
    tests: [
      { input: {}, expected: { result: 'any' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'today',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get today\'s date as text (e.g. 2026-04-10)',
    category: 'Basics',
    inputs: [],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function today() {\n  return new Date().toISOString().split("T")[0];\n}`,
      python: `from datetime import date\ndef today():\n    return date.today().isoformat()`,
    },
    tests: [
      { input: {}, expected: { result: 'any' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'date_part',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get a part of the current date (year, month, day, hour, minute, second)',
    category: 'Basics',
    inputs: [
      { name: 'part', type: 'string', description: 'Which part: year, month, day, hour, minute, second', default: 'year', choices: ['year', 'month', 'day', 'hour', 'minute', 'second', 'weekday'] },
    ],
    outputs: [{ name: 'result', type: 'any' }],
    implementations: {
      javascript: `function datePart(part) {\n  var d = new Date();\n  var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];\n  switch(part) {\n    case "year": return d.getFullYear();\n    case "month": return d.getMonth() + 1;\n    case "day": return d.getDate();\n    case "hour": return d.getHours();\n    case "minute": return d.getMinutes();\n    case "second": return d.getSeconds();\n    case "weekday": return days[d.getDay()];\n    default: return d.toISOString();\n  }\n}`,
      python: `from datetime import datetime\ndef date_part(part):\n    d = datetime.now()\n    days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]\n    parts = {"year": d.year, "month": d.month, "day": d.day, "hour": d.hour, "minute": d.minute, "second": d.second, "weekday": days[d.weekday()]}\n    return parts.get(part, d.isoformat())`,
    },
    tests: [
      { input: { part: 'year' }, expected: { result: 'any' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'days_between',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Count the days between two dates (e.g. "2026-01-01" and "2026-12-31")',
    category: 'Basics',
    inputs: [
      { name: 'date1', type: 'string', description: 'First date (YYYY-MM-DD)', default: '2026-01-01' },
      { name: 'date2', type: 'string', description: 'Second date (YYYY-MM-DD)', default: '2026-12-31' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function daysBetween(date1, date2) {\n  var d1 = new Date(date1);\n  var d2 = new Date(date2);\n  var diff = Math.abs(d2 - d1);\n  return Math.floor(diff / (1000 * 60 * 60 * 24));\n}`,
      python: `from datetime import datetime\ndef days_between(date1, date2):\n    d1 = datetime.strptime(date1, "%Y-%m-%d")\n    d2 = datetime.strptime(date2, "%Y-%m-%d")\n    return abs((d2 - d1).days)`,
    },
    tests: [
      { input: { date1: '2026-01-01', date2: '2026-01-31' }, expected: { result: 30 } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'timestamp',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the current time as a number (milliseconds since 1970)',
    category: 'Basics',
    inputs: [],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function timestamp() {\n  return Date.now();\n}`,
      python: `import time\ndef timestamp():\n    return int(time.time() * 1000)`,
    },
    tests: [
      { input: {}, expected: { result: 'number' } },
    ],
    color: '#4C97AF',
  },
  {
    name: 'null',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'The value null — means "nothing" or "no value"',
    category: 'Basics',
    inputs: [],
    outputs: [{ name: 'result', type: 'any' }],
    implementations: {
      javascript: `function cbNull() {\n  return null;\n}`,
      python: `def cb_null():\n    return None`,
    },
    tests: [],
    color: '#4C97AF',
    shape: 'value',
  },
  {
    name: 'undefined',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'The value undefined — means "not set"',
    category: 'Basics',
    inputs: [],
    outputs: [{ name: 'result', type: 'any' }],
    implementations: {
      javascript: `function cbUndefined() {\n  return undefined;\n}`,
      python: `def cb_undefined():\n    return None`,
    },
    tests: [],
    color: '#4C97AF',
    shape: 'value',
  },
  {
    name: 'infinity',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'The value Infinity — larger than any number',
    category: 'Math',
    inputs: [],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function cbInfinity() {\n  return Infinity;\n}`,
      python: `def cb_infinity():\n    return float('inf')`,
    },
    tests: [],
    color: '#5B80A5',
    shape: 'value',
  },
]
