/**
 * Gamepad blocks — read any Bluetooth/USB controller via the Web Gamepad API.
 * Works with PS4, PS5, Xbox, Switch Pro, 8BitDo, generic controllers.
 */

import type { BlockDefinition } from '../../types/block'

const COLOR = '#EA580C'
const PY_STUB = `    return False`
const PY_NUM = `    return 0`

export const gamepadBlocks: BlockDefinition[] = [
  {
    name: 'gamepad_connected',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is a game controller connected?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'connected', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_connected() { return !!(window.__gamepad && window.__gamepad.isConnected()); }`,
      python: `def gamepad_connected():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { connected: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_button_a',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is the A / Cross button pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_button_a() { return !!(window.__gamepad && window.__gamepad.buttonA()); }`,
      python: `def gamepad_button_a():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_button_b',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is the B / Circle button pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_button_b() { return !!(window.__gamepad && window.__gamepad.buttonB()); }`,
      python: `def gamepad_button_b():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_button_x',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is the X / Square button pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_button_x() { return !!(window.__gamepad && window.__gamepad.buttonX()); }`,
      python: `def gamepad_button_x():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_button_y',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is the Y / Triangle button pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_button_y() { return !!(window.__gamepad && window.__gamepad.buttonY()); }`,
      python: `def gamepad_button_y():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_dpad_up',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is D-pad Up pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_dpad_up() { return !!(window.__gamepad && window.__gamepad.dpadUp()); }`,
      python: `def gamepad_dpad_up():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_dpad_down',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is D-pad Down pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_dpad_down() { return !!(window.__gamepad && window.__gamepad.dpadDown()); }`,
      python: `def gamepad_dpad_down():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_dpad_left',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is D-pad Left pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_dpad_left() { return !!(window.__gamepad && window.__gamepad.dpadLeft()); }`,
      python: `def gamepad_dpad_left():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_dpad_right',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Is D-pad Right pressed?',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'pressed', type: 'boolean' }],
    implementations: {
      javascript: `function gamepad_dpad_right() { return !!(window.__gamepad && window.__gamepad.dpadRight()); }`,
      python: `def gamepad_dpad_right():\n${PY_STUB}`,
    },
    tests: [{ input: {}, expected: { pressed: 'boolean' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_left_stick_x',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Left stick horizontal position (-1 left to +1 right). 0 when centered.',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'x', type: 'number' }],
    implementations: {
      javascript: `function gamepad_left_stick_x() { return window.__gamepad ? window.__gamepad.leftStickX() : 0; }`,
      python: `def gamepad_left_stick_x():\n${PY_NUM}`,
    },
    tests: [{ input: {}, expected: { x: 'number' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_left_stick_y',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Left stick vertical position (-1 up to +1 down). 0 when centered.',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'y', type: 'number' }],
    implementations: {
      javascript: `function gamepad_left_stick_y() { return window.__gamepad ? window.__gamepad.leftStickY() : 0; }`,
      python: `def gamepad_left_stick_y():\n${PY_NUM}`,
    },
    tests: [{ input: {}, expected: { y: 'number' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_right_stick_x',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Right stick horizontal position (-1 left to +1 right).',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'x', type: 'number' }],
    implementations: {
      javascript: `function gamepad_right_stick_x() { return window.__gamepad ? window.__gamepad.rightStickX() : 0; }`,
      python: `def gamepad_right_stick_x():\n${PY_NUM}`,
    },
    tests: [{ input: {}, expected: { x: 'number' } }],
    color: COLOR,
    shape: 'value',
  },
  {
    name: 'gamepad_right_stick_y',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Right stick vertical position (-1 up to +1 down).',
    category: 'Games',
    inputs: [],
    outputs: [{ name: 'y', type: 'number' }],
    implementations: {
      javascript: `function gamepad_right_stick_y() { return window.__gamepad ? window.__gamepad.rightStickY() : 0; }`,
      python: `def gamepad_right_stick_y():\n${PY_NUM}`,
    },
    tests: [{ input: {}, expected: { y: 'number' } }],
    color: COLOR,
    shape: 'value',
  },
]
