import type { BlockDefinition } from '../../types/block'

export const mathBlocks: BlockDefinition[] = [
  {
    name: 'add',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Add two numbers together',
    category: 'Math',
    inputs: [
      { name: 'a', type: 'number', description: 'First number' },
      { name: 'b', type: 'number', description: 'Second number' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function add(a, b) {\n  return a + b;\n}`,
      python: `def add(a, b):\n    return a + b`,
    },
    tests: [
      { input: { a: 2, b: 3 }, expected: { result: 5 } },
      { input: { a: -1, b: 1 }, expected: { result: 0 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'subtract',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Subtract one number from another',
    category: 'Math',
    inputs: [
      { name: 'a', type: 'number', description: 'Number to subtract from' },
      { name: 'b', type: 'number', description: 'Number to subtract' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function subtract(a, b) {\n  return a - b;\n}`,
      python: `def subtract(a, b):\n    return a - b`,
    },
    tests: [
      { input: { a: 5, b: 3 }, expected: { result: 2 } },
      { input: { a: 0, b: 5 }, expected: { result: -5 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'multiply',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Multiply two numbers',
    category: 'Math',
    inputs: [
      { name: 'a', type: 'number', description: 'First number' },
      { name: 'b', type: 'number', description: 'Second number' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function multiply(a, b) {\n  return a * b;\n}`,
      python: `def multiply(a, b):\n    return a * b`,
    },
    tests: [
      { input: { a: 4, b: 5 }, expected: { result: 20 } },
      { input: { a: 0, b: 100 }, expected: { result: 0 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'divide',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Divide one number by another',
    category: 'Math',
    inputs: [
      { name: 'a', type: 'number', description: 'Number to divide' },
      { name: 'b', type: 'number', description: 'Number to divide by' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function divide(a, b) {\n  if (b === 0) return "Can't divide by zero!";\n  return a / b;\n}`,
      python: `def divide(a, b):\n    if b == 0:\n        return "Can't divide by zero!"\n    return a / b`,
    },
    tests: [
      { input: { a: 10, b: 2 }, expected: { result: 5 } },
      { input: { a: 7, b: 0 }, expected: { result: "Can't divide by zero!" } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'min_max',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Return the smaller (min) or larger (max) of two numbers',
    category: 'Math',
    inputs: [
      { name: 'mode', type: 'string', description: 'min or max', default: 'min', choices: ['min', 'max'] },
      { name: 'a', type: 'number', description: 'First number' },
      { name: 'b', type: 'number', description: 'Second number' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function minMax(mode, a, b) {\n  return mode === 'min' ? Math.min(a, b) : Math.max(a, b);\n}`,
      python: `def min_max(mode, a, b):\n    return min(a, b) if mode == 'min' else max(a, b)`,
    },
    tests: [
      { input: { mode: 'min', a: 3, b: 7 }, expected: { result: 3 } },
      { input: { mode: 'max', a: 3, b: 7 }, expected: { result: 7 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'random_number',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Pick a random number between min and max',
    category: 'Math',
    inputs: [
      { name: 'min', type: 'number', description: 'Lowest possible number', default: 1 },
      { name: 'max', type: 'number', description: 'Highest possible number', default: 100 },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function randomNumber(min, max) {\n  return Math.floor(Math.random() * (max - min + 1)) + min;\n}`,
      python: `import random\ndef random_number(min_val, max_val):\n    return random.randint(min_val, max_val)`,
    },
    tests: [
      { input: { min: 1, max: 10 }, expected: { result: 'number' } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'round',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Round a number to the nearest whole number',
    category: 'Math',
    inputs: [{ name: 'value', type: 'number', description: 'Number to round' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function roundNumber(value) {\n  return Math.round(value);\n}`,
      python: `def round_number(value):\n    return round(value)`,
    },
    tests: [
      { input: { value: 3.7 }, expected: { result: 4 } },
      { input: { value: 3.2 }, expected: { result: 3 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'power',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Raise a number to a power (like 2^3 = 8)',
    category: 'Math',
    inputs: [
      { name: 'base', type: 'number', description: 'The base number' },
      { name: 'exponent', type: 'number', description: 'The power to raise to', default: 2 },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function power(base, exponent) {\n  return Math.pow(base, exponent);\n}`,
      python: `def power(base, exponent):\n    return base ** exponent`,
    },
    tests: [
      { input: { base: 2, exponent: 3 }, expected: { result: 8 } },
      { input: { base: 5, exponent: 2 }, expected: { result: 25 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'fibonacci',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Generate the first N Fibonacci numbers',
    category: 'Math',
    inputs: [
      { name: 'n', type: 'number', description: 'How many Fibonacci numbers to generate', default: 7 },
    ],
    outputs: [{ name: 'result', type: 'any' }],
    implementations: {
      javascript: `function fibonacci(n) {\n  if (n <= 0) return [];\n  if (n === 1) return [0];\n  const result = [0, 1];\n  for (let i = 2; i < n; i++) {\n    result.push(result[i - 1] + result[i - 2]);\n  }\n  return result;\n}`,
      python: `def fibonacci(n):\n    if n <= 0:\n        return []\n    if n == 1:\n        return [0]\n    result = [0, 1]\n    for i in range(2, n):\n        result.append(result[i - 1] + result[i - 2])\n    return result`,
    },
    tests: [
      { input: { n: 7 }, expected: { result: [0, 1, 1, 2, 3, 5, 8] } },
      { input: { n: 1 }, expected: { result: [0] } },
      { input: { n: 0 }, expected: { result: [] } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'modulo',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the remainder after dividing two numbers',
    category: 'Math',
    inputs: [
      { name: 'a', type: 'number', description: 'Number to divide' },
      { name: 'b', type: 'number', description: 'Number to divide by' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function modulo(a, b) {\n  if (b === 0) return 0;\n  return a % b;\n}`,
      python: `def modulo(a, b):\n    if b == 0:\n        return 0\n    return a % b`,
    },
    tests: [
      { input: { a: 10, b: 3 }, expected: { result: 1 } },
      { input: { a: 7, b: 2 }, expected: { result: 1 } },
      { input: { a: 8, b: 4 }, expected: { result: 0 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'floor',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Round a number down to the nearest whole number',
    category: 'Math',
    inputs: [{ name: 'value', type: 'number', description: 'Number to round down' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function floor(value) {\n  return Math.floor(value);\n}`,
      python: `import math\ndef floor(value):\n    return math.floor(value)`,
    },
    tests: [
      { input: { value: 3.7 }, expected: { result: 3 } },
      { input: { value: -2.3 }, expected: { result: -3 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'ceil',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Round a number up to the nearest whole number',
    category: 'Math',
    inputs: [{ name: 'value', type: 'number', description: 'Number to round up' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function ceil(value) {\n  return Math.ceil(value);\n}`,
      python: `import math\ndef ceil(value):\n    return math.ceil(value)`,
    },
    tests: [
      { input: { value: 3.2 }, expected: { result: 4 } },
      { input: { value: -2.7 }, expected: { result: -2 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'absolute',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the absolute value of a number (always positive)',
    category: 'Math',
    inputs: [{ name: 'value', type: 'number', description: 'Number to make positive' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function absolute(value) {\n  return Math.abs(value);\n}`,
      python: `def absolute(value):\n    return abs(value)`,
    },
    tests: [
      { input: { value: -5 }, expected: { result: 5 } },
      { input: { value: 3 }, expected: { result: 3 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'square_root',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the square root of a number',
    category: 'Math',
    inputs: [{ name: 'value', type: 'number', description: 'Number to get the square root of' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function squareRoot(value) {\n  return Math.sqrt(value);\n}`,
      python: `import math\ndef square_root(value):\n    return math.sqrt(value)`,
    },
    tests: [
      { input: { value: 9 }, expected: { result: 3 } },
      { input: { value: 16 }, expected: { result: 4 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'math_pi',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'The value of Pi (3.14159...)',
    category: 'Math',
    inputs: [],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function mathPi() {\n  return Math.PI;\n}`,
      python: `import math\ndef math_pi():\n    return math.pi`,
    },
    tests: [
      { input: {}, expected: { result: 3.141592653589793 } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'min_of_list',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the smallest number in a list',
    category: 'Math',
    inputs: [
      { name: 'name', type: 'string', description: 'Name of the list' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function minOfList(name) {\n  window.__vars = window.__vars || {};\n  const list = window.__vars[name] || [];\n  return Math.min.apply(null, list);\n}`,
      python: `def min_of_list(name):\n    lst = globals().get(name, [])\n    return min(lst) if lst else 0`,
    },
    tests: [
      { input: { name: 'myList' }, expected: { result: 'number' } },
    ],
    color: '#5B80A5',
  },
  {
    name: 'max_of_list',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the largest number in a list',
    category: 'Math',
    inputs: [
      { name: 'name', type: 'string', description: 'Name of the list' },
    ],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function maxOfList(name) {\n  window.__vars = window.__vars || {};\n  const list = window.__vars[name] || [];\n  return Math.max.apply(null, list);\n}`,
      python: `def max_of_list(name):\n    lst = globals().get(name, [])\n    return max(lst) if lst else 0`,
    },
    tests: [
      { input: { name: 'myList' }, expected: { result: 'number' } },
    ],
    color: '#5B80A5',
  },
]
