import type { BlockDefinition } from '../../types/block'

export const textBlocks: BlockDefinition[] = [
  {
    name: 'uppercase',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Convert text to UPPERCASE',
    category: 'Text',
    inputs: [{ name: 'text', type: 'string', description: 'The text to convert' }],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function uppercase(text) {\n  return text.toUpperCase();\n}`,
      python: `def uppercase(text):\n    return text.upper()`,
    },
    tests: [
      { input: { text: 'hello' }, expected: { result: 'HELLO' } },
      { input: { text: 'CryptoBlocks' }, expected: { result: 'CRYPTOBLOCKS' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'lowercase',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Convert text to lowercase',
    category: 'Text',
    inputs: [{ name: 'text', type: 'string', description: 'The text to convert' }],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function lowercase(text) {\n  return text.toLowerCase();\n}`,
      python: `def lowercase(text):\n    return text.lower()`,
    },
    tests: [
      { input: { text: 'HELLO' }, expected: { result: 'hello' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'join_text',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Join two pieces of text together',
    category: 'Text',
    inputs: [
      { name: 'first', type: 'string', description: 'First text' },
      { name: 'second', type: 'string', description: 'Second text' },
    ],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function joinText(first, second) {\n  return first + second;\n}`,
      python: `def join_text(first, second):\n    return first + second`,
    },
    tests: [
      { input: { first: 'Hello, ', second: 'world!' }, expected: { result: 'Hello, world!' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'reverse_text',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Reverse any text string',
    category: 'Text',
    inputs: [{ name: 'text', type: 'string', description: 'The text to reverse' }],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function reverseText(text) {\n  return text.split('').reverse().join('');\n}`,
      python: `def reverse_text(text):\n    return text[::-1]`,
    },
    tests: [
      { input: { text: 'hello' }, expected: { result: 'olleh' } },
      { input: { text: '12345' }, expected: { result: '54321' } },
      { input: { text: '' }, expected: { result: '' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'text_length',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Count the number of characters in text',
    category: 'Text',
    inputs: [{ name: 'text', type: 'string', description: 'The text to measure' }],
    outputs: [{ name: 'length', type: 'number' }],
    implementations: {
      javascript: `function textLength(text) {\n  return text.length;\n}`,
      python: `def text_length(text):\n    return len(text)`,
    },
    tests: [
      { input: { text: 'hello' }, expected: { length: 5 } },
      { input: { text: '' }, expected: { length: 0 } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'contains',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Check if text contains a word or phrase',
    category: 'Text',
    inputs: [
      { name: 'text', type: 'string', description: 'The text to search in' },
      { name: 'search', type: 'string', description: 'What to search for' },
    ],
    outputs: [{ name: 'found', type: 'boolean' }],
    implementations: {
      javascript: `function contains(text, search) {\n  return text.includes(search);\n}`,
      python: `def contains(text, search):\n    return search in text`,
    },
    tests: [
      { input: { text: 'Hello world', search: 'world' }, expected: { found: true } },
      { input: { text: 'Hello world', search: 'xyz' }, expected: { found: false } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'replace_text',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Replace part of a text with something else',
    category: 'Text',
    inputs: [
      { name: 'text', type: 'string', description: 'The original text' },
      { name: 'find', type: 'string', description: 'What to find' },
      { name: 'replacement', type: 'string', description: 'What to replace it with' },
    ],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function replaceText(text, find, replacement) {\n  return text.replaceAll(find, replacement);\n}`,
      python: `def replace_text(text, find, replacement):\n    return text.replace(find, replacement)`,
    },
    tests: [
      { input: { text: 'Hello world', find: 'world', replacement: 'there' }, expected: { result: 'Hello there' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'to_number',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Convert text to a number',
    category: 'Text',
    inputs: [{ name: 'text', type: 'string', description: 'The text to convert', default: '0' }],
    outputs: [{ name: 'result', type: 'number' }],
    implementations: {
      javascript: `function toNumber(text) {\n  var n = Number(text);\n  return isNaN(n) ? 0 : n;\n}`,
      python: `def to_number(text):\n    try:\n        return float(text) if '.' in str(text) else int(text)\n    except (ValueError, TypeError):\n        return 0`,
    },
    tests: [
      { input: { text: '42' }, expected: { result: 42 } },
      { input: { text: '3.14' }, expected: { result: 3.14 } },
      { input: { text: 'abc' }, expected: { result: 0 } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'to_text',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Convert a number to text',
    category: 'Text',
    inputs: [{ name: 'value', type: 'number', description: 'The number to convert', default: 0 }],
    outputs: [{ name: 'result', type: 'string' }],
    implementations: {
      javascript: `function toText(value) {\n  return String(value);\n}`,
      python: `def to_text(value):\n    return str(value)`,
    },
    tests: [
      { input: { value: 42 }, expected: { result: '42' } },
      { input: { value: 3.14 }, expected: { result: '3.14' } },
    ],
    color: '#8B5CF6',
  },
  {
    name: 'split_text',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Split text into a list by a separator',
    category: 'Text',
    inputs: [
      { name: 'text', type: 'string', description: 'Text to split', default: 'hello world' },
      { name: 'separator', type: 'string', description: 'Character to split on', default: '' },
    ],
    outputs: [{ name: 'result', type: 'any' }],
    implementations: {
      javascript: `function splitText(text, separator) {\n  return String(text).split(separator);\n}`,
      python: `def split_text(text, separator):\n    return str(text).split(separator) if separator else list(str(text))`,
    },
    tests: [
      { input: { text: 'hello', separator: '' }, expected: { result: ['h', 'e', 'l', 'l', 'o'] } },
      { input: { text: 'a,b,c', separator: ',' }, expected: { result: ['a', 'b', 'c'] } },
    ],
    color: '#8B5CF6',
  },
]
