import type { BlockDefinition } from '../../types/block'

export const visionBlocks: BlockDefinition[] = [
  {
    name: 'start_camera',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Request camera access and create a hidden video element',
    category: 'Vision',
    inputs: [],
    outputs: [],
    implementations: {
      javascript: `async function startCamera() {\n  if (window.__cbCamera) return;\n  try {\n    var stream = await navigator.mediaDevices.getUserMedia({ video: true });\n    var video = document.createElement('video');\n    video.srcObject = stream;\n    video.autoplay = true;\n    video.playsInline = true;\n    video.style.display = 'none';\n    document.body.appendChild(video);\n    await new Promise(function(r) { video.addEventListener('loadedmetadata', r); });\n    window.__cbCamera = video;\n  } catch (e) {\n    console.error('Camera access denied: ' + e.message);\n  }\n}`,
      python: `def start_camera():\n    raise NotImplementedError("Camera is only supported in JavaScript")`,
    },
    tests: [],
    color: '#06B6D4',
    shape: 'statement',
  },
  {
    name: 'camera_width',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the camera video width',
    category: 'Vision',
    inputs: [],
    outputs: [{ name: 'width', type: 'number' }],
    implementations: {
      javascript: `function cameraWidth() {\n  return window.__cbCamera ? window.__cbCamera.videoWidth : 0;\n}`,
      python: `def camera_width():\n    return 0`,
    },
    tests: [],
    color: '#06B6D4',
  },
  {
    name: 'camera_height',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the camera video height',
    category: 'Vision',
    inputs: [],
    outputs: [{ name: 'height', type: 'number' }],
    implementations: {
      javascript: `function cameraHeight() {\n  return window.__cbCamera ? window.__cbCamera.videoHeight : 0;\n}`,
      python: `def camera_height():\n    return 0`,
    },
    tests: [],
    color: '#06B6D4',
  },
  {
    name: 'capture_frame',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Capture the current camera frame for pixel reading',
    category: 'Vision',
    inputs: [],
    outputs: [],
    implementations: {
      javascript: `function captureFrame() {\n  if (!window.__cbCamera) return;\n  if (!window.__cbSampler) {\n    window.__cbSampler = document.createElement('canvas');\n  }\n  var v = window.__cbCamera;\n  window.__cbSampler.width = v.videoWidth;\n  window.__cbSampler.height = v.videoHeight;\n  var ctx = window.__cbSampler.getContext('2d');\n  ctx.translate(v.videoWidth, 0);\n  ctx.scale(-1, 1);\n  ctx.drawImage(v, 0, 0);\n  ctx.setTransform(1, 0, 0, 1, 0, 0);\n  window.__cbFrameData = ctx.getImageData(0, 0, v.videoWidth, v.videoHeight);\n}`,
      python: `def capture_frame():\n    raise NotImplementedError("Camera is only supported in JavaScript")`,
    },
    tests: [],
    color: '#06B6D4',
    shape: 'statement',
  },
  {
    name: 'get_pixel_brightness',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the brightness (0–255) of the pixel at x, y from the last captured frame',
    category: 'Vision',
    inputs: [
      { name: 'x', type: 'number', description: 'X coordinate', default: 0 },
      { name: 'y', type: 'number', description: 'Y coordinate', default: 0 },
    ],
    outputs: [{ name: 'brightness', type: 'number' }],
    implementations: {
      javascript: `function getPixelBrightness(x, y) {\n  if (!window.__cbFrameData) return 0;\n  var d = window.__cbFrameData;\n  var px = Math.floor(x), py = Math.floor(y);\n  if (px < 0 || py < 0 || px >= d.width || py >= d.height) return 0;\n  var i = (py * d.width + px) * 4;\n  return Math.round((d.data[i] + d.data[i+1] + d.data[i+2]) / 3);\n}`,
      python: `def get_pixel_brightness(x, y):\n    return 0`,
    },
    tests: [],
    color: '#06B6D4',
  },
  {
    name: 'get_pixel_color',
    author: 'CryptoBlocks',
    version: '1.0.0',
    description: 'Get the hex color string of the pixel at x, y from the last captured frame',
    category: 'Vision',
    inputs: [
      { name: 'x', type: 'number', description: 'X coordinate', default: 0 },
      { name: 'y', type: 'number', description: 'Y coordinate', default: 0 },
    ],
    outputs: [{ name: 'color', type: 'string' }],
    implementations: {
      javascript: `function getPixelColor(x, y) {\n  if (!window.__cbFrameData) return '#000000';\n  var d = window.__cbFrameData;\n  var px = Math.floor(x), py = Math.floor(y);\n  if (px < 0 || py < 0 || px >= d.width || py >= d.height) return '#000000';\n  var i = (py * d.width + px) * 4;\n  var r = (d.data[i] || 0).toString(16).padStart(2, '0');\n  var g = (d.data[i+1] || 0).toString(16).padStart(2, '0');\n  var b = (d.data[i+2] || 0).toString(16).padStart(2, '0');\n  return '#' + r + g + b;\n}`,
      python: `def get_pixel_color(x, y):\n    return '#000000'`,
    },
    tests: [],
    color: '#06B6D4',
  },
]
