import { describe, it, expect, beforeEach, vi } from 'vitest'
import * as Blockly from 'blockly'

vi.mock('../crypto-unlock', () => ({
  getCryptoUnlockState: vi.fn(() => 'unlocked'),
}))

import {
  registerCustomBlocks,
  registerSingleBlock,
  generateCode,
  getToolboxXml,
} from '../blockly-register'
import { registry } from '../registry'

describe('Blockly registration', () => {
  beforeEach(() => {
    // Clear any previously registered blocks
    for (const key of Object.keys(Blockly.Blocks)) {
      if (key.startsWith('cb_')) {
        delete Blockly.Blocks[key]
      }
    }
  })

  it('registerCustomBlocks registers all blocks with Blockly', () => {
    registerCustomBlocks()

    const allBlocks = registry.getAll()
    for (const block of allBlocks) {
      expect(Blockly.Blocks[`cb_${block.name}`]).toBeDefined()
    }
  })

  it('registerSingleBlock registers one block', () => {
    const block = registry.get('print')!
    registerSingleBlock(block)

    expect(Blockly.Blocks['cb_print']).toBeDefined()
    // Other blocks should NOT be registered
    expect(Blockly.Blocks['cb_add']).toBeUndefined()
  })
})

describe('Toolbox XML', () => {
  it('includes all categories', () => {
    registerCustomBlocks()
    const xml = getToolboxXml()

    const categories = registry.getCategories()
    for (const cat of categories) {
      expect(xml).toContain(`name="${cat}"`)
    }
  })

  it('includes all block types', () => {
    registerCustomBlocks()
    const xml = getToolboxXml()

    const allBlocks = registry.getAll()
    for (const block of allBlocks) {
      expect(xml).toContain(`type="cb_${block.name}"`)
    }
  })

  it('includes built-in value blocks', () => {
    const xml = getToolboxXml()
    expect(xml).toContain('type="math_number"')
    expect(xml).toContain('type="text"')
    expect(xml).toContain('type="logic_boolean"')
  })
})

describe('Code generation', () => {
  beforeEach(() => {
    registerCustomBlocks()
  })

  it('generates JS code for a workspace with blocks', () => {
    const workspace = new Blockly.Workspace()
    const block = workspace.newBlock('cb_print')

    // Connect a text value
    const textBlock = workspace.newBlock('text')
    textBlock.setFieldValue('Hello World', 'TEXT')
    block.getInput('message')!.connection!.connect(textBlock.outputConnection!)

    const code = generateCode(workspace, 'javascript')

    expect(code).toContain('// Generated by CryptoBlocks')
    expect(code).toContain('function print(message)')
    expect(code).toContain('print("Hello World")')

    workspace.dispose()
  })

  it('generates Python code for a workspace with blocks', () => {
    const workspace = new Blockly.Workspace()
    const block = workspace.newBlock('cb_print')

    const textBlock = workspace.newBlock('text')
    textBlock.setFieldValue('Hello World', 'TEXT')
    block.getInput('message')!.connection!.connect(textBlock.outputConnection!)

    const code = generateCode(workspace, 'python')

    expect(code).toContain('# Generated by CryptoBlocks')
    expect(code).toContain('def print_message(message)')
    expect(code).toContain('print_message("Hello World")')

    workspace.dispose()
  })

  it('adds await prefix for async blocks', () => {
    const workspace = new Blockly.Workspace()
    workspace.newBlock('cb_wait')

    const code = generateCode(workspace, 'javascript')
    expect(code).toContain('await wait(')

    workspace.dispose()
  })

  it('generates code for HTTP blocks with await', () => {
    const workspace = new Blockly.Workspace()
    const block = workspace.newBlock('cb_http_get')

    const urlBlock = workspace.newBlock('text')
    urlBlock.setFieldValue('https://api.example.com', 'TEXT')
    block.getInput('url')!.connection!.connect(urlBlock.outputConnection!)

    const code = generateCode(workspace, 'javascript')
    expect(code).toContain('await httpGet(')
    expect(code).toContain('async function httpGet(url)')

    workspace.dispose()
  })

  it('generates empty program comment for empty workspace', () => {
    const workspace = new Blockly.Workspace()

    const jsCode = generateCode(workspace, 'javascript')
    expect(jsCode).toContain('// Generated by CryptoBlocks')

    const pyCode = generateCode(workspace, 'python')
    expect(pyCode).toContain('# Generated by CryptoBlocks')

    workspace.dispose()
  })
})
