import type { SharedProject } from '../types/shareplace'

export const MOCK_PROJECTS: SharedProject[] = [
  {
    id: '1',
    name: '2048 Clone',
    author: 'blockwizard',
    description: 'A fully playable 2048 game built entirely with blocks. Swipe to merge tiles and reach the 2048 tile — if you can!',
    category: 'Games',
    blockCount: 312,
    downloads: 1847,
    likes: 204,
    createdAt: '2026-03-28',
    tags: ['game', 'puzzle', 'classic'],
  },
  {
    id: '2',
    name: 'Snake Game',
    author: 'retro_coder',
    description: 'Classic snake game with keyboard controls, score tracking, and increasing speed. Hits the wall and it is game over.',
    category: 'Games',
    blockCount: 178,
    downloads: 923,
    likes: 88,
    createdAt: '2026-03-20',
    tags: ['game', 'retro', 'arcade'],
  },
  {
    id: '3',
    name: 'Flappy Bird',
    author: 'pipedreamer',
    description: 'Tap to fly through the pipes. Built with canvas blocks and a tight game loop — surprisingly hard to put down.',
    category: 'Games',
    blockCount: 145,
    downloads: 2010,
    likes: 317,
    createdAt: '2026-02-14',
    tags: ['game', 'arcade', 'canvas'],
  },
  {
    id: '4',
    name: 'Spirograph Generator',
    author: 'curvy_artist',
    description: 'Create mesmerizing spirograph patterns by tweaking radius, step size, and color hue. Every parameter combo produces something new.',
    category: 'Art',
    blockCount: 89,
    downloads: 541,
    likes: 122,
    createdAt: '2026-03-15',
    tags: ['art', 'math', 'canvas', 'generative'],
  },
  {
    id: '5',
    name: 'Pixel Art Maker',
    author: 'dot_matrix',
    description: 'Draw pixel art on a 16x16 grid. Pick a color, click to paint, and export your masterpiece as a data URL.',
    category: 'Art',
    blockCount: 134,
    downloads: 388,
    likes: 67,
    createdAt: '2026-03-05',
    tags: ['art', 'drawing', 'grid'],
  },
  {
    id: '6',
    name: 'Calculator',
    author: 'mathmatician',
    description: 'A fully functional calculator with keyboard support, order of operations, and a clear history panel. Nothing fancy, just works.',
    category: 'Web',
    blockCount: 97,
    downloads: 1204,
    likes: 145,
    createdAt: '2026-02-20',
    tags: ['math', 'utility', 'beginner'],
  },
  {
    id: '7',
    name: 'Weather Dashboard',
    author: 'cloud_builder',
    description: 'Fetches live weather from Open-Meteo and renders a styled card with temperature, wind speed, and a condition icon.',
    category: 'Web',
    blockCount: 203,
    downloads: 671,
    likes: 91,
    createdAt: '2026-03-10',
    tags: ['api', 'weather', 'dashboard'],
  },
  {
    id: '8',
    name: 'Todo App',
    author: 'taskmaster9',
    description: 'A clean todo list with add, complete, and delete. Data persists in localStorage so your tasks survive a refresh.',
    category: 'Web',
    blockCount: 118,
    downloads: 856,
    likes: 103,
    createdAt: '2026-02-28',
    tags: ['productivity', 'storage', 'beginner'],
  },
  {
    id: '9',
    name: 'Drum Machine',
    author: 'beatbuilder',
    description: 'Step-sequencer with 8 drum pads and a 16-step grid. Toggle steps to build patterns, adjust BPM, and loop your beat.',
    category: 'Sound',
    blockCount: 261,
    downloads: 488,
    likes: 79,
    createdAt: '2026-03-22',
    tags: ['music', 'audio', 'sequencer'],
  },
  {
    id: '10',
    name: 'Piano Keys',
    author: 'keyboardkid',
    description: 'Play piano in the browser with two octaves of keys. Uses the Web Audio API for clean sine-wave tones on each press.',
    category: 'Sound',
    blockCount: 74,
    downloads: 312,
    likes: 54,
    createdAt: '2026-03-01',
    tags: ['music', 'audio', 'keyboard'],
  },
  {
    id: '11',
    name: 'Quiz App',
    author: 'quizmistress',
    description: 'A trivia quiz engine. Define your questions in a list block, shuffle them, track score, and show a summary at the end.',
    category: 'Data',
    blockCount: 156,
    downloads: 299,
    likes: 41,
    createdAt: '2026-02-18',
    tags: ['education', 'quiz', 'lists'],
  },
  {
    id: '12',
    name: 'Crypto Tracker',
    author: 'satoshi_fan',
    description: 'Polls the CoinGecko API to display live prices for BTC, ETH, and SOL. Color-coded for 24h change. Auto-refreshes every 30 seconds.',
    category: 'Data',
    blockCount: 187,
    downloads: 734,
    likes: 138,
    createdAt: '2026-03-18',
    tags: ['crypto', 'api', 'finance', 'live-data'],
  },
]
